import { Router } from "express";
import { createProduct, getAllProducts, getCategory, getCategoryWiseProduct, getProducts, getSingleProduct } from "../controller/product.controller.js";
const productRouter = Router();
productRouter.post("/create", createProduct);
productRouter.get("/category", getCategory);
productRouter.get("/product", getProducts);
productRouter.get("/products", getAllProducts);
productRouter.get("/:category", getCategoryWiseProduct);
productRouter.get("/product/:_id", getSingleProduct);
export default productRouter;
